### ISSUE TITLE
ReplicaSetConnection

### ISSUE THREAD

**Issue by gpitfield** [django-nonrel/mongodb-engine#104]
Has anyone tried using pymongo's ReplicaSetConnection instead of just a vanilla Connection? I'm planning to give it a try, didn't see anything about this, but would sure appreciate hearing if anything's been done/tried/abandoned etc. Seems like it might be cleaner than always specifying read and write db's explicitly...

**Comment by markunsworth** [comment]
This is now resolved. Should be closed
