### ISSUE TITLE
PyMongo compatibility with latest version

### ISSUE THREAD

**Issue by Zygonie** [django-nonrel/mongodb-engine#209]
Hi,
I dont know which version of PyMongo is used under the hood, but I tried to install mongodb-engine to use my database hosted on compose.io, but I got an error "ConfigurationError: Unknown option auto_start_request". I saw in the doc of PyMongo that "The pool_size, auto_start_request, and timeout parameters for Connection have been completely removed in this release. They were deprecated in pymongo-1.4 and have had no effect since then. Please make sure that your code doesn’t currently pass these parameters when creating a Connection instance." so I suspect my issue is link to that ? Is it possible as a workaround to downgrade the version of PyMongo until this issue is fixed as I cannot use it and work on my project ?

**Comment by jlines** [comment]
I have run into this same issue.

**Comment by markunsworth** [comment]
I have a branch which is set to work with pymongo >= 3.0, however it's not backwards compatible due to the large number of breaking changes in this release of pymongo. 

If people feel this is ok, I would be happy to submit a pull request

**Comment by aburgel** [comment]
See #214
